USE [master]
GO

/****** Object:  Database [Homework01]    Script Date: 6/16/2021 4:03:39 AM ******/
CREATE DATABASE [Homework01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Homework01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Homework01.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Homework01_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Homework01_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Homework01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Homework01] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Homework01] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Homework01] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Homework01] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Homework01] SET ARITHABORT OFF 
GO

ALTER DATABASE [Homework01] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Homework01] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Homework01] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Homework01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Homework01] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Homework01] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Homework01] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Homework01] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Homework01] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Homework01] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Homework01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Homework01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Homework01] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Homework01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Homework01] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Homework01] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Homework01] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Homework01] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Homework01] SET  MULTI_USER 
GO

ALTER DATABASE [Homework01] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Homework01] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Homework01] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Homework01] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Homework01] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Homework01] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Homework01] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Homework01] SET  READ_WRITE 
GO

